### PR TITLE
Low power sleep

### PR DESCRIPTION
**Pull request by hja685**
added a low power sketch that uses assembly. The attached sketch is for the arduino 328P. I also forgot to change my branch back when doing a successful compilation of the arduino CAN code.

### CODE REVIEW

**Comment by hja685** [comment]
I changed elements within lines of code here. I'm not sure how the conflict resolution works. It would be nice if you can accept all changes as the "master" file does not compile currently, and this pull request file does compile successfully.

**Comment by bengardiner-at-irdeto** [comment]
this LGTM. but you'll need to resolve the conflicts to enable merging

---

From the security assessment POV this is looking great because there is really no data-dependent execution at all, so it's hard to imagine how the behaviour could be influenced from the ELD-side (or vehicle side).

I'll keep reviewing periodically. I'd like to review a debug build `.elf` file for both AVRs sometime also.

**Comment by hja685** [comment]
Resolving conflicts will be done today.

**Comment by hja685** [comment]
@jeremydaily could you please review this

**Review by jeremydaily — APPROVED** [review]
Looks ok. It's a step in the right direction.

**Pull request merged**
